### ISSUE TITLE
Padding negatief kan niet

### ISSUE THREAD

**Issue by Anna-Kyra** [Akikosophia/the-startup-responsive-interactieve-website#13]
```CSS
 .separator {
    position: relative;
    width: 100px;
    height: 300px;
    margin-bottom: -300px;
    padding-bottom: -100px;
  }
```

<img width="1521" alt="Scherm­afbeelding 2024-01-19 om 12 20 50" src="https://github.com/Akikosophia/the-startup-responsive-interactieve-website/assets/144000242/950a1cd6-0ecc-4b9b-bd8b-4f174321b548">

Je kan geen negatieve `padding` hebben. Een negatieve `margin` is beter hiervoor.
