### ISSUE TITLE
Form input lengte

### ISSUE THREAD

**Issue by Anna-Kyra** [Akikosophia/the-startup-responsive-interactieve-website#14]
```CSS
input  {
    padding: 5px 5px 5px 125px;
    background-color: var(--form-color);
    border: none;
}
```

De length van je input van je forms is niet even. Je kan `width: 100%` voor je `input` gebruiken.
