### ISSUE TITLE
Img centreren

### ISSUE THREAD

**Issue by Anna-Kyra** [Akikosophia/the-startup-responsive-interactieve-website#5]
```CSS
.illustration-img {
  object-fit: cover;
  width: 150px;
  margin-left:95px;
  margin-right:100px;
}
```
[Permalink](https://github.com/Akikosophia/the-startup-responsive-interactieve-website/blob/b484540c3af37971184ed673b50e538fbb0770ca/style.css#L162C1-L167C2)

Je image staan niet gecentreerd en wilt dat wel doen doormiddel van je `margin`.

Ik zou `margin: auto` gebruiken om ze te centreren.
